import "./About.css";
import Navbar from "../../components/Navbar/Navbar.jsx";

function About() {
  return (
    <div className="about">
      <Navbar />
      <div className="abt-hero">
        <h1>
          About AiThink <i className="ri-planet-line"></i>
        </h1>
      </div>
      <div className="abt-content">
        <h1> About AiThink </h1>
        <p>
          Welcome to AiThink an Idea Aggregator — your one-stop destination for discovering
          innovative ideas, trending tech projects, and real-world inspiration
          from across the web. Whether you're a developer, student,
          entrepreneur, or curious thinker, Idea Aggregator helps you spark
          creativity by bringing together content from:
        </p>

        <ul>
          <li>
            <p>🌐 GitHub – Explore top open-source repositories.</p>
          </li>
          <li>
            <p>
              {" "}
              💡 Reddit – See what the dev and startup communities are buzzing
              about.{" "}
            </p>
          </li>
          <li>
            <p>
              🧵 X (formerly Twitter) – Follow trending posts and expert
              opinions.{" "}
            </p>
          </li>
          <li>
            <p>
              {" "}
              💭 AI-generated Ideas – Get unique project ideas generated by AI,
              tailored to your query.
            </p>
          </li>
        </ul>
      </div>

      <div className="abt-content">
        <h1> 🚀 Why We Built This</h1>
        <p>
          In today’s fast-moving tech world, finding good ideas and
          understanding what others are building is difficult. We created Idea
          Aggregator to:
        </p>

        <ul>
          <li>
            <p>Centralize inspiration from multiple platforms.</p>
          </li>
          <li>
            <p>💡 Help learners find real-world projects to build.</p>
          </li>
          <li>
            <p>Assist startups and hackers in exploring trends.</p>
          </li>
          <li>
            <p>
              Save time by delivering curated, relevant content in one place.
            </p>
          </li>
        </ul>
      </div>

      <div className="abt-content">
        <h1> 🔍 How It Works</h1>
        <ol>
          <li>
            <p>
              Enter a keyword related to your interest or domain (e.g.,
              "chatbot", "blockchain", "AI in education").
            </p>
          </li>
          <li>
            <p>
              Our system fetches the top GitHub repos, Reddit posts, X posts,
              and even generates ideas using AI.
            </p>
          </li>
          <li>
            <p>
              You get a clean, categorized view of what's trending and what's
              possible.
            </p>
          </li>
        </ol>
      </div>

      <div className="abt-content">
        <h1> 💬 Built With</h1>
        <ol>
          <li>
            <p>React + Vite for the frontend</p>
          </li>
          <li>
            <p>Express.js backend</p>
          </li>
          <li>
            <p>Material UI for sleek, responsive design</p>
          </li>
          <li>
            <p>Web scraping + APIs for real-time data fetching</p>
          </li>
          <li>
            <p>AI (OpenAI / Gemini) for intelligent idea generation</p>
          </li>
        </ol>
      </div>

      <div className="abt-content">
        <h1>🙌 Join the Movement</h1>
        <p>
          We believe great ideas spark greater actions. Whether you’re building
          your next side project, looking for internship inspiration, or just
          exploring what's new — Idea Aggregator is here to fuel your curiosity.
          Have suggestions? Want to contribute? Reach out or fork the repo on
          GitHub!
        </p>
      </div>
    </div>
  );
}

export default About;
